Repository oneleif/olWebsite, pull requests merged in 2020-02, with the labels that each got.

#56 Rename username to email in User model
  Docs/curlAPI.sh
  Docs/postmanAPI.json
  Package.resolved
  Resources/Views/Children/login.leaf
  Resources/Views/Children/register.leaf
  Sources/App/Controllers/API/ImperialController.swift
  Sources/App/Controllers/API/Requests/LoginRequest.swift
  Sources/App/Controllers/API/Requests/RegisterUserRequest.swift
  Sources/App/Controllers/API/Responses/PublicUserResponse.swift
  Sources/App/Controllers/API/SocialController.swift
  Sources/App/Controllers/API/UserController.swift
  Sources/App/Models/User.swift
  Sources/App/Services/UserService.swift
  Sources/App/configure.swift
  Tests/AppTests/Controllers/API/UserController/RegisterUserTests.swift
  Tests/AppTests/Models+Testable.swift
Labels: Backend

#57 Copy public resources and Leaf views into Docker image
  web.Dockerfile
Labels: Backend, bug

#61 Ol 60 remove leaf templating
  Package.resolved
  Package.swift
  Public/.gitkeep
  Public/images/logo.png
  Public/images/oneleif.png
  Public/images/sign-in-with-github.png
  Public/images/sign-in-with-google.png
  Public/scripts/cookies.js
  Public/styles.css
  Resources/Views/Children/authIndex.leaf
  Resources/Views/Children/authPost.leaf
  Resources/Views/Children/authPosts.leaf
  Resources/Views/Children/createPost.leaf
  Resources/Views/Children/dashboard.leaf
  Resources/Views/Children/index.leaf
  Resources/Views/Children/login.leaf
  Resources/Views/Children/post.leaf
  Resources/Views/Children/posts.leaf
  Resources/Views/Children/register.leaf
  Resources/Views/Children/social.leaf
  Resources/Views/authBase.leaf
  Resources/Views/base.leaf
  Sources/App/Controllers/AuthRouteController.swift
  Sources/App/Controllers/BaseRouteController.swift
  Sources/App/Controllers/Contexts.swift
  Sources/App/Controllers/ImageController.swift
  Sources/App/Controllers/ImperialController.swift
  Sources/App/Controllers/PostController.swift
  Sources/App/Controllers/Requests/LoginRequest.swift
  Sources/App/Controllers/Requests/RegisterUserRequest.swift
  Sources/App/Controllers/Responses/ErrorResponse.swift
  Sources/App/Controllers/Responses/PublicUserResponse.swift
  Sources/App/Controllers/SocialController.swift
  Sources/App/Controllers/UserController.swift
  Sources/App/configure.swift
  Sources/App/routes.swift
  web.Dockerfile
Labels: enhancement

#62 Open API Documentation
  Public/docs/index.html
  Public/docs/swagger.yml
  Public/logo.png
  web.Dockerfile
Labels: Backend, documentation

#63 Deploy new release to AWS on push to master
  .circleci/config.yml
  Deploy/appspec.yml
  Deploy/hooks/after.sh
  Deploy/hooks/validate.sh
Labels: Backend, enhancement
