Repository oneleif/olWebsite, pull requests merged in 2020-03, with the labels that each got.

#70 Feature/use postgre sql
  .circleci/config.yml
  Package.resolved
  Package.swift
  Sources/App/Controllers/PostController.swift
  Sources/App/Controllers/SocialController.swift
  Sources/App/Controllers/UserController.swift
  Sources/App/Models/PostItem.swift
  Sources/App/Models/User.swift
  Sources/App/Services/UserService.swift
  Sources/App/configure.swift
  Tests/AppTests/Application+Testable.swift
  Tests/AppTests/Controllers/API/UserController/RegisterUserTests.swift
  Tests/AppTests/Models+Testable.swift
  Tests/AppTests/Services/ValidatorServiceTests.swift
  Tests/LinuxMain.swift
  docker-compose.yml
Labels: Backend, enhancement

#76 Update README.md
  README.md
Labels: enhancement

#75 Feature/login info social docs
  Sources/App/Controllers/SocialController.swift
  Sources/App/Controllers/UserController.swift
Labels: documentation, enhancement

#78 Deploy develop branch to AWS staging on every push
  .circleci/config.yml
  Deploy/appspec.yml
  Deploy/hooks/after.sh
  Deploy/hooks/validate.sh
  docker-compose.yml
Labels: Backend

#86 JWT tokens & auth
  .circleci/config.yml
  Package.swift
  Public/docs/swagger.yml
  Sources/App/Controllers/ImageController.swift
  Sources/App/Controllers/ImperialController.swift
  Sources/App/Controllers/PostController.swift
  Sources/App/Controllers/Requests/RefreshTokenRequest.swift
  Sources/App/Controllers/Responses/AccessTokenResponse.swift
  Sources/App/Controllers/Responses/LoginResponse.swift
  Sources/App/Controllers/SocialController.swift
  Sources/App/Controllers/UserController.swift
  Sources/App/Models/AccessToken.swift
  Sources/App/Models/RefreshToken.swift
  Sources/App/Models/User.swift
  Sources/App/Services/AuthService.swift
  Sources/App/Services/UserService.swift
  Sources/App/Utilities/JWT/JWTConfig.swift
  Sources/App/Utilities/JWT/JWTError.swift
  Sources/App/Utilities/JWT/JWTMiddleware.swift
  Sources/App/Utilities/JWT/Payloads/AccessTokenPayload.swift
  Sources/App/Utilities/JWT/TokenHelpers.swift
  Sources/App/Utilities/Request+AuthorizedUser.swift
  Sources/App/configure.swift
  Tests/AppTests/Controllers/UserController/LoginTests.swift
  Tests/AppTests/Controllers/UserController/LogoutTests.swift
  Tests/AppTests/Controllers/UserController/RefreshTokenTests.swift
  Tests/AppTests/Controllers/UserController/RegisterUserTests.swift
  Tests/LinuxMain.swift
Labels: Backend, enhancement

#87 Hotfix/fix building docker image
  .circleci/config.yml
  Sources/App/Controllers/ImageController.swift
  Sources/App/Controllers/SocialController.swift
Labels: Backend, bug
